### ISSUE TITLE
Unable to mount PV to EKS node after upgrading to v1.26

### ISSUE THREAD

**Issue by KqLLL** [aws/eks-distro#2080]
**What happened**:
We have some PVs that cannot mount PVs to EKS nodes after upgrading to v1.26. We investigated that these PVs were configured with the labels `failure-domain.beta.kubernetes.io/region` and `failure-domain.beta.kubernetes.io/zone` and we use the `ebs-cis-driver`(EKS addons) manage these storage.

Upstream, the node label is listed as deprecated, but unless I missed it, I don't see any announcement or indication that the label is being removed at 1.26. The only reference I see is here:
https://kubernetes.io/docs/reference/labels-annotations-taints/#failure-domainbetakubernetesioregion

I'm curious, why is that?

**What you expected to happen**:
I expected these breaking changes to be in the EKS release notes, because these change affect our production services.

**How to reproduce it (as minimally and precisely as possible)**:
An example:
```yaml
apiVersion: v1 
kind: PersistentVolume
metadata:
  name: pvc-9bfda38d-b956-438d-8256-697be08519a0
  uid: 087a5d48-9005-4157-9aa7-5a0087668314
  labels:
    failure-domain.beta.kubernetes.io/region: us-east-2
    failure-domain.beta.kubernetes.io/zone: us-east-2a
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://us-east-2a/vol-05bca6cf13c58966a
  capacity:
    storage: 8Gi
# The nodeAffinity is not important in this Issue. 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-east-2a
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - us-east-2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  volumeMode: Filesystem
```
**Anything else we need to know?**:

**Environment**:
- EKS Distro Release Channel: AWS Official
- EKS Distro Release:  v1.26.2-eks-b106822
